import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
// import grid from "/../assets/images/grid.svg"
export const metadata = {
  title: 'Parth Movaliya',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}
  : {
    children: React.ReactNode
  }
) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='main'>
          <div className="gradient" />
        </div>
        <div className="">
          {children}
        </div>
      </body>
    </html >
  )
}
